switch to the new ci user name/reference
Nordix/metal3-dev-tools pull request #489
Opened 2022-02-17 10:44 UTC by Rozzii

2022-02-17 10:44 UTC, Rozzii commented
/hold

2022-02-18 07:15 UTC, smoshiur1237 reviewed
LGTM

2022-02-18 09:19 UTC, furkatgofurov7 requested changes

2022-02-18 09:19 UTC, furkatgofurov7 commented on scripts/run_metal3_vm.sh
> +  grep "airship-ci-ubuntu-metal3-img" | awk '{print $5}' \
airship?

2022-02-18 09:19 UTC, furkatgofurov7 commented on scripts/run_metal3_vm.sh
> +  openstack image save --file "$WORK_DIR/ubuntu_metal3.qcow2" airship-ci-ubuntu-metal3-img
why airship?

2022-02-18 09:24 UTC, Rozzii commented on ci/jobs/capi_bm_units_tests.pipeline
> +git_credential_id = "nordix-metal3-ci-github-prod-token"
Thanks I have pushed to gerrit related to this please check, I have requested a review from you.

2022-02-18 09:24 UTC, Rozzii commented on scripts/run_metal3_vm.sh
> +  grep "airship-ci-ubuntu-metal3-img" | awk '{print $5}' \
I will change this, it was reset when we weren't sure about the order of changing the images but it can be metal3 already.

2022-02-18 09:25 UTC, Rozzii commented on scripts/run_metal3_vm.sh
> +  openstack image save --file "$WORK_DIR/ubuntu_metal3.qcow2" airship-ci-ubuntu-metal3-img
I will change this, it was reset when we weren't sure about the order of changing the images but it can be metal3 already.

2022-02-18 09:37 UTC, furkatgofurov7 approved these changes

2022-02-18 09:38 UTC, merged