Update CAPO docs and scripts
Nordix/metal3-dev-tools pull request #510
Opened 2022-03-23 10:06 UTC by lentzi90

- Bumped CAPI version
- Bumped kubernetes version
- Bumped yq version (v4 is now supported in CAPO)
- Updated docs and added cleanup instructions

2022-03-25 14:53 UTC, smoshiur1237 requested changes

2022-03-25 14:53 UTC, smoshiur1237 commented on capo/README.md
> +If you followed the suggestion to change the name of the cluster it would be whatever you chose, e.g. `${USER}-capo-test`.
same "you"

2022-03-28 05:43 UTC, lentzi90 commented
Thanks for the review @smoshiur1237 ! I'm a bit hesitant to remove the "you" here because we already had it in multiple places before my changes.
These docs are very specific for developers in our team, not general user guides, so I think it is ok to refer to the developer as "you". It makes it clearer what the developer can choose (e.g. cluster name), and what is common guidelines that everyone has to follow.

2022-03-28 07:12 UTC, smoshiur1237 reviewed
LGTM

2022-04-04 08:53 UTC, smoshiur1237 approved these changes

2022-04-04 09:06 UTC, merged