add support for custom config-drive in IPA part 2
Nordix/metal3-dev-tools pull request #646
Opened 2023-01-10 11:59 UTC by Rozzii

This commit introduces the following changes:
    
        - New ipa-file-injector service that can inject files
          from config-drive with a custom label during userspace boot.
        - ipa-file-injector expects a manifest to be present on the
          config-drive to contain key-value pairs in a ":" separated
          format that specify source and destination paths for the
          files that are planned to be copied.
        - Custom label used by the ipa-file-injector can be specified during
          the IPA build process.

2023-01-10 11:59 UTC, Rozzii commented
/hold
Part 1 has to be merged first, then I will rebase this.

2023-01-10 12:47 UTC, tuminoid requested changes

2023-01-10 12:47 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/install.d/99-enable-ipa-file-injector
> +set -o pipefail
No pipes, not needed.

2023-01-10 12:47 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/install.d/99-enable-ipa-file-injector
> +set -eu
The only variable -u could take effect is above it. Maybe move it to the top. set -e also makes most sense when its at very start.

2023-01-10 12:47 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/99-install-file-injector
> +[ -n "$TARGET_ROOT" ]
This would be 100% better if you exit with a message, than just exit because it fails and -e kicks you out. Also, missing braces.

2023-01-10 12:47 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +function copy_files_from_drive {
With explicit bash, `function x {` is deprecated, and should use `x() {` style functions.

2023-01-10 12:47 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +    local MOUNT_POINT="${1}"
While braces work with `${1}` etc, it is best-practice for single character variables to use plain `$1`, unless you're doing some expansion for them.

2023-01-10 12:47 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +if [[ "${TYPE}" == 'vfat' ]]; then
You're using `[` in previous if, and now `[[` which is not necessary. Unless you use bash-specific advanced comparison, like regex, single = and single [ is the way to go.

2023-01-10 12:47 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +    mount -t vfat -o umask=0077 "${BLOCKDEV}" "${MOUNT_POINT}" || true
What's the point of `|| true`, since it'll just defer failure to `copy_files_from_drive` and make it harder to debug?

2023-01-10 12:47 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/override-simple-init/post-install.d/99-override-simple-init
> +set -o pipefail
Same nit as earlier about the set lines.

2023-01-10 12:47 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +    done <"${MANIFEST}"
Add a space after `<` for readability.

2023-01-10 12:47 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +function copy_files_from_drive {
This function is also used exactly once, so it doesn't really help. Probably would be earlier to read, and less lines, if it was inline where function is called.

2023-01-10 13:42 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/install.d/99-enable-ipa-file-injector
> +set -o pipefail
Thanks, fixed!

2023-01-10 13:42 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/install.d/99-enable-ipa-file-injector
> +set -eu
Thanks, fixed!

2023-01-10 13:43 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +    local MOUNT_POINT="${1}"
Thanks, fixed!

2023-01-10 13:43 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/99-install-file-injector
> +[ -n "$TARGET_ROOT" ]
Thanks, fixed!

2023-01-10 13:47 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/override-simple-init/post-install.d/99-override-simple-init
> +set -o pipefail
Thanks, fixed!

2023-01-10 13:47 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +    done <"${MANIFEST}"
Thanks, fixed!

2023-01-10 13:49 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +if [[ "${TYPE}" == 'vfat' ]]; then
Thanks, fixed!

2023-01-10 13:53 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +    mount -t vfat -o umask=0077 "${BLOCKDEV}" "${MOUNT_POINT}" || true
I don't think it is hard to debug, there will be a error message saved related to the read command on the ipa-file-injector service' status page. It can be checked with systemctl status.

2023-01-10 13:55 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +    mount -t vfat -o umask=0077 "${BLOCKDEV}" "${MOUNT_POINT}" || true
But I will implement something a bit more sophisticated some pre-check for example why not.

2023-01-10 14:29 UTC, Rozzii commented
/test-metal3-fullstack

2023-01-10 15:57 UTC, Rozzii commented
/test-metal3-fullstack

2023-01-12 10:13 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +    mount -t vfat -o umask=0077 "${BLOCKDEV}" "${MOUNT_POINT}" || true
Done.
I have modified the error handling process.

2023-01-12 11:38 UTC, tuminoid requested changes
Some nits, but also one thing to fix.

2023-01-12 11:38 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/install.d/99-enable-ipa-file-injector
> +set -e
Add `-u` back, and move to the top of the script.

2023-01-12 11:38 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/99-install-file-injector
> +set -e
Same here

2023-01-12 11:38 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/99-install-file-injector
> +if [ -z "$TARGET_ROOT" ]; then
Missing braces.

2023-01-12 11:38 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +        cp -r "${MOUNT_POINT}/${src}" "${dst}"
You can write `if ! cp -r ...` directly, saves you trouble of assigning CPY_RESULT, and if clause.  It also prevents script from failing when `set -e` is active (which it isn't, you should add `set -eu` on top, since if catches the failure.

2023-01-12 11:38 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +
Add `set -eu` on top.

2023-01-12 11:38 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +    mount -t vfat -o umask=0077 "${BLOCKDEV}" "${MOUNT_POINT}"
I see you removed `|| true` here, but at the cost of removing `set -e`. `set -e` is always better choice than cleaning up `|| true`. As you explained in the comment, you prefer to defer failure to the copy_files function, so its design choice, and its commented as well.

2023-01-12 11:38 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/override-simple-init/post-install.d/99-override-simple-init
> +set -e
Same here.

2023-01-12 11:47 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +        cp -r "${MOUNT_POINT}/${src}" "${dst}"
I am conciously not using set -e in this script, i want this to fail only at those locations where I have implemented error handling, if it fails in other places like blkid commands or mount, then that is fine from the perspecitve of this service those are tolerated, it is also fine if some or all of the copy fails, missing files are also tolerated the script will fail at the end but I want it to try to execute all to copy actions.

I can do the if cp -r  I agree that is a bit more lean.

2023-01-12 11:49 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +
It is  by design, only specific command failures are considered service failure.

2023-01-12 11:50 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +    mount -t vfat -o umask=0077 "${BLOCKDEV}" "${MOUNT_POINT}"
It is by design, only specific command failures are considered service failure.

but I see now you prefer the explicit || true so I will turn the things around add add back the || true  .

2023-01-12 12:06 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +
I see your point now, I will change it.

2023-01-12 12:06 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +        cp -r "${MOUNT_POINT}/${src}" "${dst}"
I will change the set -eu back too, I see your point .

2023-01-12 12:09 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/install.d/99-enable-ipa-file-injector
> +set -e
done

2023-01-12 12:10 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/99-install-file-injector
> +if [ -z "$TARGET_ROOT" ]; then
done

2023-01-12 12:10 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/99-install-file-injector
> +set -e
done

2023-01-12 12:10 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +        cp -r "${MOUNT_POINT}/${src}" "${dst}"
done

2023-01-12 12:10 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +    mount -t vfat -o umask=0077 "${BLOCKDEV}" "${MOUNT_POINT}"
done

2023-01-12 12:10 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/override-simple-init/post-install.d/99-override-simple-init
> +set -e
done

2023-01-12 12:10 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +
done

2023-01-12 12:51 UTC, tuminoid requested changes

2023-01-12 12:51 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/99-install-file-injector
> +if [ -z "${TARGET_ROOT}" ]; then
Now that we have `set -u` this will fail if TARGET_ROOT is undefined. If only triggers the error if TARGET_ROOT is empty. You want to have `if [ -z "${TARGET_ROOT:-}" ]; ...`. Sorry for missing this on previous round.

2023-01-12 12:54 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/99-install-file-injector
> +if [ -z "${TARGET_ROOT}" ]; then
I think it is fine if it is a hard failure here, TARGET_ROOT is a must have in DIB, if this is missing I think it is ok to fail as that would mean that there is some issue with the base os element. Also the TARGET_ROOT is dynamically generated so there is no default value for it.

2023-01-12 13:20 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/99-install-file-injector
> +if [ -z "${TARGET_ROOT}" ]; then
OK, in that case it might warrant a comment to say it is intentional. Helps the next guy who has to debug it to know where the fault lies.

2023-01-12 13:39 UTC, Rozzii commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/99-install-file-injector
> +if [ -z "${TARGET_ROOT}" ]; then
Done.

2023-01-13 07:48 UTC, tuminoid approved these changes
One comment on semantics, but it works both ways, so lgtm on scripting pov.

2023-01-13 07:48 UTC, tuminoid commented on ci/scripts/image_scripts/ipa_builder_elements/ipa-file-injector/root.d/ipa-file-injector.sh
> +    if ! [ -f "${MANIFEST}" ]; then
Typically the `!` is inside the `[]`, but it works like this as well. Semantics about is it the `[` (ie. `test` command) flipping the result of a test, or `if` flipping the return value of `[`.

2023-01-13 07:53 UTC, merged