Fix shellcheck script for running in a container, shellcheck issues and remove unnecessary files
Nordix/metal3-dev-tools pull request #647
Opened 2023-01-12 12:49 UTC by kashifest

2023-01-12 13:10 UTC, tuminoid requested changes
More to come, it was refreshed while reviewing.

2023-01-12 13:10 UTC, tuminoid commented on ci/images/gen_metal3_ubuntu_image.sh
> +  PROVISIONING_SCRIPTS="($(find "${CI_DIR}"/scripts/image_scripts | grep -E 'provision_(node|metal3)_image_ubuntu.sh'))"
Same here.

2023-01-12 13:10 UTC, tuminoid commented on ci/scripts/image_scripts/node-image-cloud-init/retrieve.configuration.files.sh
> +http_status=$(< "${tmpfile}" tail -n 1)
It's trying to tell you to do just `tail -1 "${tmpfile}"`

2023-01-12 13:10 UTC, tuminoid commented on ci/scripts/image_scripts/node-image-cloud-init/retrieve.configuration.files.sh
> +  < "${tmpfile}" sed '$d' > "${dst}";
Same here. `sed '$d' "${tmpfile}" > "${dst}"` is enough.

2023-01-12 13:10 UTC, tuminoid commented on ci/scripts/image_scripts/provision_node_image_centos.sh
> +echo "$PATH"|tr ':' '\n'
Add missing braces while at it?

2023-01-12 13:10 UTC, tuminoid commented on ci/scripts/image_scripts/provision_node_image_ubuntu.sh
> +sudo mv "$SCRIPTS_DIR"/node-image-cloud-init/retrieve.configuration.files.sh /usr/local/bin/retrieve.configuration.files.sh
Braces here as well

2023-01-12 13:17 UTC, tuminoid requested changes

2023-01-12 13:17 UTC, tuminoid commented on ci/scripts/image_scripts/run_fetch_logs.sh
> -if [ ! -z "${target_config}" ]
This is WRONG. You changed meaning of the if from "if non-empty" to "if empty". Shellcheck wants to you change `! -z` to `-n` which mean the same thing (non empty).

2023-01-12 13:17 UTC, tuminoid commented on ci/scripts/image_scripts/run_fetch_logs.sh
> +  fetch_k8s_logs "target_cluster" "$target_config"
Missing braces.

2023-01-12 13:17 UTC, tuminoid commented on ci/scripts/image_scripts/run_fetch_logs.sh
> +tar -cvzf "$LOGS_TARBALL" "${LOGS_DIR}"/*
Same.

2023-01-12 13:17 UTC, tuminoid commented on scripts/shellcheck.sh
> +    /workdir/scripts/shellcheck.sh "${@}"
As discussed, change `${@}` to `$@`, its bash3 compatible and also the best-pracice.

2023-01-12 13:17 UTC, tuminoid commented on tools/scalability/setup_vms.sh
> +ips=$(< vm_ip_list.txt tr '\n' ' ')
Same as before, just pass the file as argument to tr.

2023-01-12 13:17 UTC, tuminoid commented on tools/scalability/setup_vms.sh
>  set -xe
Add `-u`?

2023-01-12 13:17 UTC, tuminoid commented on tools/scalability/setup_vms.sh
>  for ip in $ips;do
Add missing space

2023-01-12 13:17 UTC, tuminoid commented on tools/scalability/setup_vms.sh
> +master_vm_ip=$(< vm_ip_list.txt head -n 1 )
You probably know what I want you to change at this point :)

2023-01-12 13:17 UTC, tuminoid commented on tools/scalability/setup_vms.sh
> +	if [[ $ip == "$master_vm_ip" ]]; then
My eyes bleed at that if, but its consistent with the script, so it can wait another time....

2023-01-12 13:17 UTC, tuminoid commented on wow/jenkins_ci/jenkins-check-ci.sh
> +nbr_of_lines=$(< jenkins-jobs-to-scan.txt wc -l)
Same old, same old. Note that `wc` output changes a little when its given an actual file instead of stdin feed.

2023-01-12 18:51 UTC, kashifest commented on ci/images/gen_base_ubuntu_image.sh
> +# shellcheck disable=SC1090,SC1091
Done

2023-01-12 18:51 UTC, kashifest commented on ci/images/gen_metal3_centos_image.sh
> +  FINAL_IMAGE_NAME=${FINAL_IMAGE_NAME:-"CENTOS_${CENTOS_VERSION}_NODE_IMAGE_K8S_""${KUBERNETES_VERSION}"}
Done

2023-01-12 18:52 UTC, kashifest commented on ci/images/gen_metal3_centos_image.sh
> +  PROVISIONING_SCRIPTS="($(find "${CI_DIR}"/scripts/image_scripts | grep -E 'provision_(node|metal3)_image_centos.sh'))"
Done, your example was missing quotes for `CI_DIR` but I have added it.

2023-01-12 18:52 UTC, kashifest commented on ci/images/gen_metal3_ubuntu_image.sh
> +  PROVISIONING_SCRIPTS="($(find "${CI_DIR}"/scripts/image_scripts | grep -E 'provision_(node|metal3)_image_ubuntu.sh'))"
Done

2023-01-12 18:53 UTC, kashifest commented on ci/scripts/image_scripts/node-image-cloud-init/retrieve.configuration.files.sh
> +http_status=$(< "${tmpfile}" tail -n 1)
Done

2023-01-12 18:53 UTC, kashifest commented on ci/scripts/image_scripts/node-image-cloud-init/retrieve.configuration.files.sh
> +  < "${tmpfile}" sed '$d' > "${dst}";
Done

2023-01-12 18:53 UTC, kashifest commented on ci/scripts/image_scripts/provision_node_image_centos.sh
> +echo "$PATH"|tr ':' '\n'
Done

2023-01-12 18:53 UTC, kashifest commented on ci/scripts/image_scripts/provision_node_image_ubuntu.sh
> +sudo mv "$SCRIPTS_DIR"/node-image-cloud-init/retrieve.configuration.files.sh /usr/local/bin/retrieve.configuration.files.sh
Done

2023-01-12 18:53 UTC, kashifest commented on ci/scripts/image_scripts/run_fetch_logs.sh
> -if [ ! -z "${target_config}" ]
Good catch, done

2023-01-12 18:53 UTC, kashifest commented on ci/scripts/image_scripts/run_fetch_logs.sh
> +tar -cvzf "$LOGS_TARBALL" "${LOGS_DIR}"/*
Done

2023-01-12 18:54 UTC, kashifest commented on ci/scripts/image_scripts/run_fetch_logs.sh
> +  fetch_k8s_logs "target_cluster" "$target_config"
Done

2023-01-12 18:55 UTC, kashifest commented on tools/scalability/setup_vms.sh
> +ips=$(< vm_ip_list.txt tr '\n' ' ')
Done

2023-01-12 18:55 UTC, kashifest commented on tools/scalability/setup_vms.sh
>  for ip in $ips;do
Done

2023-01-12 18:55 UTC, kashifest commented on tools/scalability/setup_vms.sh
> +master_vm_ip=$(< vm_ip_list.txt head -n 1 )
Done

2023-01-12 18:55 UTC, kashifest commented on wow/jenkins_ci/jenkins-check-ci.sh
> +nbr_of_lines=$(< jenkins-jobs-to-scan.txt wc -l)
Done

2023-01-12 18:55 UTC, kashifest commented
@tuminoid PTAL again.

2023-01-12 18:56 UTC, kashifest commented
/test-integration-metal3-dev-tools-ubuntu 
/test-integration-metal3-dev-tools-centos

2023-01-13 06:57 UTC, kashifest commented
/test-integration-metal3-dev-tools-ubuntu
/test-integration-metal3-dev-tools-centos

2023-01-13 07:03 UTC, kashifest commented
/test-integration-metal3-dev-tools-ubuntu

2023-01-13 07:06 UTC, kashifest commented
/test-integration-metal3-dev-tools-ubuntu
/test-integration-metal3-dev-tools-centos

2023-01-13 07:10 UTC, kashifest commented
/test-integration-metal3-dev-tools-ubuntu

2023-01-13 07:42 UTC, tuminoid requested changes
One actual bug, and some other comments.

2023-01-13 07:42 UTC, tuminoid commented on ci/scripts/image_scripts/install_crio_on_ubuntu.sh
> +cat <<EOF | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:"$CRIO_VERSION".list
Missing braces.

2023-01-13 07:42 UTC, tuminoid commented on ci/scripts/image_scripts/install_crio_on_ubuntu.sh
> +curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/"$OS"/Release.key | sudo apt-key --keyring /etc/apt/trusted.gpg.d/libcontainers.gpg add -
Missing braces, both lines.

2023-01-13 07:42 UTC, tuminoid commented on ci/scripts/image_scripts/start_centos_fullstack_build.sh
> +#shellcheck source=ci/scripts/openstack/utils.sh
Put the space back between `#` and `shellcheck`.

2023-01-13 07:42 UTC, tuminoid commented on ci/scripts/image_scripts/upload_node_image_rt.sh
> +#shellcheck source=ci/scripts/artifactory/utils.sh
Put the space back between `#` and `shellcheck`.

2023-01-13 07:42 UTC, tuminoid commented on ci/scripts/jumphost/create_or_update_dev_jumphost.sh
> +#shellcheck source=ci/scripts/artifactory/utils.sh
Put the space back between `#` and `shellcheck`. x3

2023-01-13 07:42 UTC, tuminoid commented on ci/scripts/jumphost/del_jumphost_user.sh
> +#shellcheck source=ci/scripts/artifactory/utils.sh
Put the space back between `#` and `shellcheck`. x4

2023-01-13 07:42 UTC, tuminoid commented on ci/scripts/jumphost/delete_dev_jumphost.sh
> +#shellcheck source=ci/scripts/artifactory/utils.sh
Put the space back between `#` and `shellcheck`. x3

2023-01-13 07:42 UTC, tuminoid commented on ci/scripts/jumphost/update_dev_jumphost_users.sh
> +#shellcheck source=ci/scripts/artifactory/utils.sh
Put the space back between `#` and `shellcheck`.

2023-01-13 07:42 UTC, tuminoid commented on tools/scalability/setup_vms.sh
> +	if [[ $ip == "$master_vm_ip" ]]; then
`$ip` should be doublequoted as well. If it resolves to empty string, then it'll break the syntax.

Also, since you're touching most of the lines with having missing braces, maybe fix them while at it? `$ip`, `$master_vm_ip` etc.

2023-01-13 07:42 UTC, tuminoid commented on wow/jenkins_ci/jenkins-check-ci.sh
> +nbr_of_lines=$(wc -l jenkins-jobs-to-scan.txt)
I warned about this in previous review. If `wc` is passed an actual filename, then it'll include that filename in the output. This is now assigning `10 jenkins-jobs-to-scan.txt` to variable, instead of just `10`.

Use `wc -l < jenkins-jobs-to-scan.txt` to restore original functionality.

2023-01-13 07:42 UTC, tuminoid commented on wow/jenkins_ci/jenkins-check-ci.sh
> +if [[ -n "$out" ]]; then
Missing braces, if you want to fix it in one pass. `$out`, `$all_pass`, `$nbr_of_lines` and `$count`.

2023-01-13 08:29 UTC, kashifest commented
/test-integration-metal3-dev-tools-ubuntu
/test-integration-metal3-dev-tools-centos

2023-01-13 08:29 UTC, kashifest commented
Thanks again @tuminoid . PTAL again

2023-01-13 08:33 UTC, tuminoid submitted a review, later dismissed
lgtm

2023-01-13 08:48 UTC, lentzi90 submitted a review, later dismissed
This was a breath of fresh air. Thank you for fixing!
/lgtm

2023-01-13 08:57 UTC, furkatgofurov7 reviewed
Nice one, few nits:

2023-01-13 08:57 UTC, furkatgofurov7 commented on ci/scripts/jumphost/del_jumphost_user.sh
> +# shellcheck source=ci/scripts/openstack/utils.sh
should be `source=ci/scripts/openstack/infra_defines.sh`

2023-01-13 08:57 UTC, furkatgofurov7 commented on ci/scripts/jumphost/create_or_update_dev_jumphost.sh
> +# shellcheck source=ci/scripts/openstack/utils.sh
same

2023-01-13 08:57 UTC, furkatgofurov7 commented on ci/scripts/jumphost/delete_dev_jumphost.sh
> +# shellcheck source=ci/scripts/openstack/utils.sh
same as above

2023-01-13 08:57 UTC, furkatgofurov7 commented on resources/docker/gotest/Dockerfile
> -ENV GOLANG_VERSION 1.13rc2
this is ancient :)

2023-01-13 12:16 UTC, kashifest commented
/test-integration-metal3-dev-tools-ubuntu
/test-integration-metal3-dev-tools-centos

2023-01-13 12:27 UTC, furkatgofurov7 approved these changes

2023-01-13 14:00 UTC, merged