add retries to apt and packer
Nordix/metal3-dev-tools pull request #648
Opened 2023-01-17 08:03 UTC by Rozzii

This commit adds retires to apt and packer commands involved in openstack,jumphost,base and node image building.

2023-01-17 08:14 UTC, tuminoid requested changes

2023-01-17 08:14 UTC, tuminoid commented on ci/scripts/image_scripts/setup_chrony_ubuntu.sh
> +sudo echo 'Acquire::Retries "10";' > /etc/apt/apt.conf.d/80-retries
Don't put any code above `set -eu` as it might fail and set wouldn't catch it.

2023-01-17 09:01 UTC, Rozzii commented on ci/scripts/image_scripts/setup_chrony_ubuntu.sh
> +sudo echo 'Acquire::Retries "10";' > /etc/apt/apt.conf.d/80-retries
there is no set -eu in the script

2023-01-17 09:04 UTC, Rozzii commented on ci/scripts/image_scripts/setup_chrony_ubuntu.sh
> +sudo echo 'Acquire::Retries "10";' > /etc/apt/apt.conf.d/80-retries
done

2023-01-17 09:06 UTC, Rozzii commented
> Do we really need to put the apt config in all these scripts? Is it not enough to put it in `provision_*.sh` scripts that then call the other scripts?

I was not sure about all teh use-cases of all the script, just wanted to be sure that the retries are there, if you think it is not needed everywhere i can put it only to provision scripts

2023-01-17 10:01 UTC, tuminoid approved these changes
lgtm

2023-01-17 10:19 UTC, lentzi90 commented
> > Do we really need to put the apt config in all these scripts? Is it not enough to put it in `provision_*.sh` scripts that then call the other scripts?
> 
> I was not sure about all the use-cases of all the scripts, just wanted to be sure that the retries are there, if you think it is not needed everywhere i can put it only to provision scripts

I'm fairly certain that they are only ever used by the provision scripts. Did a quick search through the repo for any references and could not find any other than those scripts.
Strictly speaking the metal3 and jenkins images are also built on the base image so we would only need it in base and node provision scripts, but that could change in the future. I would anyway suggest to add it only in the provision scripts.

2023-01-17 12:30 UTC, Rozzii commented
/retest

2023-01-17 12:31 UTC, kashifest commented
> /retest

I am fixing the shellcheck issues in my new PR. It wont pass until that merges

2023-01-17 12:43 UTC, Rozzii commented
/test-integration-metal3-dev-tools-centos

2023-01-17 13:46 UTC, Rozzii commented
/retest

2023-01-17 13:46 UTC, Rozzii commented
/approved

2023-01-17 13:47 UTC, Rozzii commented
/approve

2023-01-18 06:13 UTC, Rozzii commented
/test-integration-metal3-dev-tools-ubuntu

2023-01-18 08:16 UTC, Rozzii commented
/test-integration-metal3-dev-tools-ubuntu

2023-01-18 12:57 UTC, kashifest approved these changes

2023-01-18 12:57 UTC, merged