fix run_local image builder script
Nordix/metal3-dev-tools pull request #654
Opened 2023-02-10 14:17 UTC by Rozzii

- fix failing parameter expension of the container env vars (this was caused by shellcheck related refactoring)

- remove unnecessary container env vars

- add timestamp to the generated image otherwise in case of

  subsequent image builds the openstack client won't be abel to distinguish between the images and won't save the new image

- introduce more explicit variable nameing in certain cases

- remove key_pair variable from the packer vars as it is not needed and just complicates the script

- restrict openstack related logic into the container, so nothing that talks to openstack will be executed outside the container thus there is no need to have the ostack client installed on the host system

- add sandbox mode, in case the user would like to look around in ostack without building an image

- add interactive debug mode for the packer building process, user can wait between packer build steps thus the build vm won't disappear in case of an issue

Co-authored-by: Lennart Jern lennart.jern@est.tech

2023-02-10 14:21 UTC, Rozzii commented
/test-integration-metal3-dev-tools-centos
/test-integration-metal3-dev-tools-ubuntu

2023-02-13 06:47 UTC, lentzi90 requested changes
Nice job! This is definitely improving many things!

Could you also update the readme also so it matches?
https://github.com/Nordix/metal3-dev-tools/blob/main/ci/images/README.md?plain=1#L87-L175

2023-02-13 06:47 UTC, lentzi90 commented on ci/images/run_local.sh
> +fi
Nice!

2023-02-13 06:47 UTC, lentzi90 commented on ci/images/run_local.sh
> +IMAGE_DATE="$(date +"%Y-%m-%dT%H-%M-%S%z")"
While it is nice to avoid name collisions, I do like to be able to set the exact name when I build an image, but I can always rename them of course. Another thing to think about is that this makes it easier to forget about old images when you don't have to remove them before building a new with the same name. Also, deleting them becomes a bit harder when you have to check the exact name to get the date correct.
What do you think about checking if the image name is already taken before starting the build? I don't have a strong opinion on this myself. Adding the date is fine, just wanted to raise some drawbacks and discuss alternatives. :slightly_smiling_face:

2023-02-13 08:29 UTC, tuminoid requested changes
Some nits. One error found. Change the shebang to `#!/usr/bin/env bash` as well. `run_local.sh` is specifically meant to be executed on user's machine.

2023-02-13 08:29 UTC, tuminoid commented on ci/images/run_local.sh
> +KUBERNETES_VERSION=${KUBERNETES_VERSION:-"v1.26.0"}
Quotes go around the whole expression, not needed inside the braces.

2023-02-13 08:29 UTC, tuminoid commented on ci/images/run_local.sh
> +CR_CMD_ENV=("--env" "OS_AUTH_URL"
Please put each "--env ..." on separate line, including the first and last one. Makes diffs cleaner if touched later on.

2023-02-13 08:29 UTC, tuminoid commented on ci/images/run_local.sh
> +  "${CONTAINER_RUNTIME}" "run --rm -ti"\
`"run --rm -ti"` is interpreted as single word, and won't work. No need to quote them.

2023-02-13 08:29 UTC, tuminoid commented on ci/images/run_local.sh
> +if [[ "$PROVISIONING_SCRIPT" == *"node"* ]]; then
Braces.

2023-02-13 08:29 UTC, tuminoid commented on ci/images/run_local.sh
> +  CR_CMD_ENV+=("--env" "RT_URL"
Each value on separate line.

2023-02-14 14:17 UTC, Rozzii commented on ci/images/run_local.sh
> +KUBERNETES_VERSION=${KUBERNETES_VERSION:-"v1.26.0"}
done.

2023-02-14 14:17 UTC, Rozzii commented on ci/images/run_local.sh
> +  CR_CMD_ENV+=("--env" "RT_URL"
done.

2023-02-14 14:17 UTC, Rozzii commented on ci/images/run_local.sh
> +CR_CMD_ENV=("--env" "OS_AUTH_URL"
done

2023-02-14 14:19 UTC, Rozzii commented on ci/images/run_local.sh
> +if [[ "$PROVISIONING_SCRIPT" == *"node"* ]]; then
done

2023-02-14 14:20 UTC, Rozzii commented
/test-integration-metal3-dev-tools-centos
/test-integration-metal3-dev-tools-ubuntu

2023-02-14 14:22 UTC, tuminoid commented on ci/images/README.md
> +export NETWORK_NAME="ext-net"
It would be helpful if difference between these two and expected content would be clearer here for both `NETWORK` and `NETWORK_NAME`.

2023-02-14 14:22 UTC, tuminoid commented on ci/images/README.md
> +export NO_IMAGE_CLEANUP="true/false" # if ture deletes the image from openstack that has an equivalent
ture -> true

2023-02-15 06:49 UTC, lentzi90 commented on ci/images/README.md
> +appends a timestamp to the name of each newly built image to avoid collision
Continuing the comments on the next line looks strange since it is not syntax highlighted in the same way. It also makes it harder to copy this snippet. I would suggest putting the comments on their own line(s) completely or at least add a `#` on the continuing lines.

2023-02-15 06:49 UTC, lentzi90 commented on ci/images/run_local.sh
> +IMAGE_DATE="$(date +"%Y-%m-%dT%H-%M-%S%z")"
Nice!
Can we drop the `NO_` from `NO_IMAGE_CLEANUP`? It is easier to understand and reason about it if the variable in itself doesn't have extra negations IMO. :sweat_smile: So just `IMAGE_CLEANUP="true/false"

2023-02-15 07:47 UTC, Rozzii commented on ci/images/run_local.sh
> +IMAGE_DATE="$(date +"%Y-%m-%dT%H-%M-%S%z")"
Sure, done.

2023-02-15 07:47 UTC, Rozzii commented on ci/images/README.md
> +export NETWORK_NAME="ext-net"
added some explanation and made the names a bit more explicit.

2023-02-15 07:47 UTC, Rozzii commented on ci/images/README.md
> +export NO_IMAGE_CLEANUP="true/false" # if ture deletes the image from openstack that has an equivalent
done.

2023-02-15 07:47 UTC, Rozzii commented on ci/images/README.md
> +appends a timestamp to the name of each newly built image to avoid collision
done.

2023-02-15 07:55 UTC, Rozzii commented
/test-integration-metal3-dev-tools-centos
/test-integration-metal3-dev-tools-ubuntu

2023-02-15 08:19 UTC, lentzi90 commented on ci/images/README.md
> +                                  # appends a timestamp to the name of each newly built image to avoid collision
One last thing, I think we have true/false backwards here. IMAGE_CLEANUP=true should delete, false should add the timestamp

2023-02-15 08:21 UTC, tuminoid approved these changes
Looks good from my pov

2023-02-15 08:22 UTC, tuminoid commented
/hold
Let's make sure we have all the reviews in.

2023-02-15 08:23 UTC, Rozzii commented on ci/images/README.md
> +                                  # appends a timestamp to the name of each newly built image to avoid collision
Just mixed up the description, nice find.

2023-02-15 08:41 UTC, Rozzii commented
/test-integration-metal3-dev-tools-ubuntu
/test-integration-metal3-dev-tools-centos

2023-02-15 08:45 UTC, lentzi90 approved these changes
/lgtm

2023-02-15 08:45 UTC, lentzi90 commented
/hold cancel

2023-02-15 09:42 UTC, merged